name: Chainsaw
main: me.BerylliumOranges.main.PluginMain
version: 0.1
api-version: '1.20'
commands:
   getitems:
      description: Gets all the Purity plugin's items.
      aliases: null
      permission: null
      usage: /<command>
   checkitem:
      description: testing only.
      aliases: null
      permission: null
      usage: /<command>
   potions:
      description: Check what potions are still active.
      aliases: null
      permission: null
      usage: /<command>
   gpt:
      description: Talk with chatgpt.
      aliases: null
      permission: null
      usage: /<command>
   goto:
      description: Teleport to a dimension
      aliases: null
      permission: null
      usage: /<command> <dimension name>
   listdimensions:
      description: Lists all dimensions
      aliases: null
      permission: null
      usage: /<command>
   createdimension:
      description: Create a dimension
      aliases: null
      permission: null
      usage: /<command> <name>
   deletedimension:
      description: Unload a dimension
      aliases: null
      permission: null
      usage: /<command> <name>
   spawnboss:
      description: Spawn a boss
      aliases: null
      permission: null
      usage: /<command> <boss id (integer)>